In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [69]:
import requests, json
from pandas import DataFrame

In [19]:
typo_url = "https://www.msyamkumar.com/hello.txttttttt"
r = requests.get(typo_url)
assert r.status_code == 200
#r.text

AssertionError:

In [20]:
#Simple string example
url = "https://www.msyamkumar.com/hello.txt"
r = requests.get(url)
r.raise_for_status() #shortcut for asserting status code is 200 OK

In [21]:
r.text

'Hello CS220 students! Welcome to my website. Hope you are staying safe and healthy!\n'

In [30]:
#JSON example
url = "https://www.msyamkumar.com/scores.json"
r = requests.get(url)
r.raise_for_status()
urltext = r.text

#json.load(FILE_OBJECT)
#json.loads(STRING)
print(type(json.loads(urltext)))
#d = json.loads(urltext)

#Shortcut for json.loads
d = r.json()
print(d)

<class 'dict'>
{'alice': 100, 'bob': 200, 'cindy': 300}

In [42]:
#DEMO 1: reddit json processing

#url = "https://www.reddit.com/r/UWMadison.json"
#This does not work due to 429 status code!
url = "https://www.msyamkumar.com/cs220/s20/materials/lectureDemo_code/lec-31/UWMadison.json"
r = requests.get(url)
r.raise_for_status()
#r.json()
print(type(r.json()))

<class 'dict'>

In [44]:
d = r.json()
print(d.keys())

print(d["kind"])
#print(d["data"])

dict_keys(['kind', 'data'])
Listing

In [46]:
type(d["data"])
d["data"].keys()

dict_keys(['modhash', 'dist', 'children', 'after', 'before'])

In [50]:
print(type(d["data"]["children"]))
d["data"]["children"].keys()

<class 'list'>

AttributeError: 'list' object has no attribute 'keys'

In [56]:
for item in d["data"]["children"]:
    #print(type(item))
    #print(type(item["data"]))
    #print(item["data"].keys())
    print(item["data"]["score"], item["data"]["title"])

15 COVID-19 Megathread
10 Admissions Megathread
13 Newest apartment decoration
63 it's voting day badgers
2 Best ECE Classes
163 Stay Strong Badgers
8 Business courses recommendations
2 Easy Intermediate Lib. Studies Courses?
2 Taking Micro 101 and Anatomy (Kines 337) over the summer too much?
45 Gap Semester
2 Recommendation about Classics 340
1 Biochem 551
5 CS 537 (OS): group projects?
14 Chance of grad admission being rescinded?
2 ECON 521 with Sandholm?
2 Parking costs in the Madison area
13 Does anyone know how to get a witness signature for absentee voting?
2 Software/Hardware class in Fall 2020
4 Summer online courses: ECON 302 and Account 300
11 Please help a fellow prospect CS student!
3 Grading scale for Math 141
81 Does anyone need a car?
135 To the person playing On Wisconsin near Johnson and University
0 Prospective CS Student and AP Credit
5 CNA Job as a Student??
0 A few questions
1 Is this a course overload?

In [64]:
#DEMO 3: State Populations

prefixURL = "https://www.msyamkumar.com/cs220/s20/materials/lectureDemo_code/lec-31/data/"
r = requests.get(prefixURL + "state_files.txt")
r.raise_for_status()
stateFiles = r.text.split("\n")
stateFiles

['Alabama.json',
 'Alaska.json',
 'Arizona.json',
 'Arkansas.json',
 'California.json',
 'Colorado.json',
 'Connecticut.json',
 'Delaware.json',
 'Florida.json',
 'Georgia.json',
 'Hawaii.json',
 'Idaho.json',
 'Illinois.json',
 'Indiana.json',
 'Iowa.json',
 'Kansas.json',
 'Kentucky.json',
 'Louisiana.json',
 'Maine.json',
 'Maryland.json',
 'Massachusetts.json',
 'Michigan.json',
 'Minnesota.json',
 'Mississippi.json',
 'Missouri.json',
 'Montana.json',
 'Nebraska.json',
 'Nevada.json',
 'New_Hampshire.json',
 'New_Jersey.json',
 'New_Mexico.json',
 'New_York.json',
 'North_Carolina.json',
 'North_Dakota.json',
 'Ohio.json',
 'Oklahoma.json',
 'Oregon.json',
 'Pennsylvania.json',
 'Rhode_Island.json',
 'South_Carolina.json',
 'South_Dakota.json',
 'Tennessee.json',
 'Texas.json',
 'Utah.json',
 'Vermont.json',
 'Virginia.json',
 'Washington.json',
 'West_Virginia.json',
 'Wisconsin.json',
 'Wyoming.json']

In [74]:
rows = []

for state in stateFiles:
    url = prefixURL + state
    r = requests.get(url)
    r.raise_for_status()
    data = r.json()
    data["name"] = state
    rows.append(data)

df = DataFrame(rows)
df

        2000      2010      2015                 name
0    4447100   4779736   4846411         Alabama.json
1     626932    710231    737046          Alaska.json
2    5130632   6392017   6728783         Arizona.json
3    2673400   2915918   2966835        Arkansas.json
4   33871648  37253956  38792291      California.json
5    4301261   5029196   5355588        Colorado.json
6    3405565   3574097   3594762     Connecticut.json
7     783600    897934    935968        Delaware.json
8   15982378  18801310  19905569         Florida.json
9    8186453   9687653  10097132         Georgia.json
10   1211537   1360301   1420257          Hawaii.json
11   1293953   1567582   1634806           Idaho.json
12  12419293  12830632  12882189        Illinois.json
13   6080485   6483802   6597880         Indiana.json
14   2926324   3046355   3109481            Iowa.json
15   2688418   2853118   2902507          Kansas.json
16   4041769   4339367   4412617        Kentucky.json
17   4468976   4533372   4648990       Louisiana.json
18   1274923   1328361   1330256           Maine.json
19   5296486   5773552   5975346        Maryland.json
20   6349097   6547629   6755124   Massachusetts.json
21   9938444   9883640   9916306        Michigan.json
22   4919479   5303925   5457125       Minnesota.json
23   2844658   2967297   2993443     Mississippi.json
24   5595211   5988927   6063827        Missouri.json
25    902195    989415   1023252         Montana.json
26   1711263   1826341   1882980        Nebraska.json
27   1998257   2700551   2838281          Nevada.json
28   1235786   1316470   1327996   New_Hampshire.json
29   8414350   8791894   8938844      New_Jersey.json
30   1819046   2059179   2085567      New_Mexico.json
31  18976457  19378102  19748858        New_York.json
32   8049313   9535483   9940387  North_Carolina.json
33    642200    672591    740040    North_Dakota.json
34  11353140  11536504  11596998            Ohio.json
35   3450654   3751351   3879610        Oklahoma.json
36   3421399   3831074   3971202          Oregon.json
37  12281054  12702379  12793767    Pennsylvania.json
38   1048319   1052567   1054907    Rhode_Island.json
39   4012012   4625364   4829160  South_Carolina.json
40    754844    814180    853304    South_Dakota.json
41   5689283   6346105   6547779       Tennessee.json
42  20851820  25145561  26979078           Texas.json
43   2233169   2763885   2944498            Utah.json
44    608827    625741    626767         Vermont.json
45   7078515   8001024   8328098        Virginia.json
46   5894121   6724540   7063166      Washington.json
47   1808344   1852994   1848751   West_Virginia.json
48   5363675   5686986   5759432       Wisconsin.json
49    493782    563626    584304         Wyoming.json

In [77]:
df.head()
df_state = df.set_index("name")

In [78]:
df_state.sum()

2000    280849847
2010    308143815
2015    318247565
dtype: int64

In [79]:
df_state.T

name,Alabama.json,Alaska.json,Arizona.json,Arkansas.json,California.json,Colorado.json,Connecticut.json,Delaware.json,Florida.json,Georgia.json,...,South_Dakota.json,Tennessee.json,Texas.json,Utah.json,Vermont.json,Virginia.json,Washington.json,West_Virginia.json,Wisconsin.json,Wyoming.json
2000,4447100,626932,5130632,2673400,33871648,4301261,3405565,783600,15982378,8186453,...,754844,5689283,20851820,2233169,608827,7078515,5894121,1808344,5363675,493782
2010,4779736,710231,6392017,2915918,37253956,5029196,3574097,897934,18801310,9687653,...,814180,6346105,25145561,2763885,625741,8001024,6724540,1852994,5686986,563626
2015,4846411,737046,6728783,2966835,38792291,5355588,3594762,935968,19905569,10097132,...,853304,6547779,26979078,2944498,626767,8328098,7063166,1848751,5759432,584304

In [80]:
df_state.T.mean()

name
Alabama.json           4.691082e+06
Alaska.json            6.914030e+05
Arizona.json           6.083811e+06
Arkansas.json          2.852051e+06
California.json        3.663930e+07
Colorado.json          4.895348e+06
Connecticut.json       3.524808e+06
Delaware.json          8.725007e+05
Florida.json           1.822975e+07
Georgia.json           9.323746e+06
Hawaii.json            1.330698e+06
Idaho.json             1.498780e+06
Illinois.json          1.271070e+07
Indiana.json           6.387389e+06
Iowa.json              3.027387e+06
Kansas.json            2.814681e+06
Kentucky.json          4.264584e+06
Louisiana.json         4.550446e+06
Maine.json             1.311180e+06
Maryland.json          5.681795e+06
Massachusetts.json     6.550617e+06
Michigan.json          9.912797e+06
Minnesota.json         5.226843e+06
Mississippi.json       2.935133e+06
Missouri.json          5.882655e+06
Montana.json           9.716207e+05
Nebraska.json          1.806861e+06
Nevada.json            2.512363e+06
New_Hampshire.json     1.293417e+06
New_Jersey.json        8.715029e+06
New_Mexico.json        1.987931e+06
New_York.json          1.936781e+07
North_Carolina.json    9.175061e+06
North_Dakota.json      6.849437e+05
Ohio.json              1.149555e+07
Oklahoma.json          3.693872e+06
Oregon.json            3.741225e+06
Pennsylvania.json      1.259240e+07
Rhode_Island.json      1.051931e+06
South_Carolina.json    4.488845e+06
South_Dakota.json      8.074427e+05
Tennessee.json         6.194389e+06
Texas.json             2.432549e+07
Utah.json              2.647184e+06
Vermont.json           6.204450e+05
Virginia.json          7.802546e+06
Washington.json        6.560609e+06
West_Virginia.json     1.836696e+06
Wisconsin.json         5.603364e+06
Wyoming.json           5.472373e+05
dtype: float64